---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Check for tabs in shell scripts
        run: |
          ! grep -P "^\t" --line-number *.sh
      - name: Run ShellCheck
        run: |
          shellcheck *.sh

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    needs: shellcheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Build image
        run: make
      - name: Save image as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: alpine-airgap-images
          path: |
            alpine-airgap-*.iso
          retention-days: 7
