---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Check for tabs in shell scripts
        run: |
          ! grep -P "^\t" --line-number build.sh
      - name: Run ShellCheck
        run: shellcheck build.sh

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    needs: shellcheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Build image
        run: make
